/****************************ENTITY***********************************/
export const ADD_ENTITY_LOADING = 'ADD_ENTITY_LOADING';
export const ADD_ENTITY_SUCCESS = 'ADD_ENTITY_SUCCESS';
export const ADD_ENTITY_FAIL = 'ADD_ENTITY_FAIL';

export const EDIT_ENTITY_LOADING = 'EDIT_ENTITY_LOADING';
export const EDIT_ENTITY_SUCCESS = 'EDIT_ENTITY_SUCCESS';
export const EDIT_ENTITY_FAIL = 'EDIT_ENTITY_FAIL';

export const DELETE_ENTITY_LOADING = 'DELETE_ENTITY_LOADING';
export const DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS';
export const DELETE_ENTITY_FAIL = 'DELETE_ENTITY_FAIL';

export const GET_ENTITIES_LOADING = 'GET_ENTITIES_LOADING';
export const GET_ENTITIES_SUCCESS = 'GET_ENTITIES_SUCCESS';
export const GET_ENTITIES_FAIL = 'GET_ENTITIES_FAIL';


/***************************TRANSACTION**********************************/
export const ADD_TRANSACTION_LOADING = 'ADD_TRANSACTION_LOADING';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const ADD_TRANSACTION_FAIL = 'ADD_TRANSACTION_FAIL';

export const EDIT_TRANSACTION_LOADING = 'EDIT_TRANSACTION_LOADING';
export const EDIT_TRANSACTION_SUCCESS = 'EDIT_TRANSACTION_SUCCESS';
export const EDIT_TRANSACTION_FAIL = 'EDIT_TRANSACTION_FAIL';

export const DELETE_TRANSACTION_LOADING = 'DELETE_TRANSACTION_LOADING';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAIL = 'DELETE_TRANSACTION_FAIL';

export const GET_TRANSACTIONS_LOADING = 'GET_TRANSACTIONS_LOADING';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAIL = 'GET_TRANSACTIONS_FAIL';

/***************************AUTH**********************************/

export const LOGIN_WITH_OAUTH_LOADING = 'LOGIN_WITH_OAUTH_LOADING';
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_OAUTH_SUCCESS';
export const LOGIN_WITH_OAUTH_FAIL = 'LOGIN_WITH_OAUTH_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const USER_LOADING = 'USER_LOADING';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAIL = 'USER_FAIL';

/****************************Analytics****************************/

export const GET_TRENDS_LOADING = 'GET_TRENDS_LOADING';
export const GET_TRENDS_SUCCESS = 'GET_TRENDS_SUCCESS';
export const GET_TRENDS_FAIL = 'GET_TRENDS_FAIL';

export const GET_ENTITY_ANALYTICS_LOADING = 'GET_ENTITY_ANALYTICS_LOADING';
export const GET_ENTITY_ANALYTICS_SUCCESS = 'GET_ENTITY_ANALYTICS_SUCCESS';
export const GET_ENTITY_ANALYTICS_FAIL = 'GET_ENTITY_ANALYTICS_FAIL';

export const GET_CASHFLOW_ANALYTICS_LOADING = 'GET_CASHFLOW_ANALYTICS_LOADING';
export const GET_CASHFLOW_ANALYTICS_SUCCESS = 'GET_CASHFLOW_ANALYTICS_SUCCESS';
export const GET_CASHFLOW_ANALYTICS_FAIL = 'GET_CASHFLOW_ANALYTICS_FAIL';